[versions]
fabric-loader = "0.19.3"
fabric-kotlin = "1.13.12+kotlin.2.4.0"
stonecutter = "0.10-alpha.2"
mod-publish-plugin = "2.1.1"
kotlin = "2.4.0"

[libraries]
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-loader-junit = { group = "net.fabricmc", name = "fabric-loader-junit", version.ref = "fabric-loader" }
fabric-language-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }
stonecutter = { group = "dev.kikugie", name = "stonecutter", version.ref = "stonecutter" }
mod-publish-plugin = { group = "me.modmuss50", name = "mod-publish-plugin", version.ref = "mod-publish-plugin" }
kotlin-jvm = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }